soyiss/Qpc

- src/main/resources/templates/component/adminNav.html
> adminNav기본모달추가

- src/main/resources/templates/component/sidebar.html
sidebar_(신욱님이전커밋내용지워서다시합침)/form삭제및memberFood
> sidebar_(이전커밋내용지워서다시합침)

- src/main/resources/templates/component/adminNav.html
> 카테고리 alert 수정

- src/main/resources/templates/component/adminNav.html
adminNav-모달창 추가
-게임관리
-게임등록
-게임수정
-게임삭제
> Html0717 5

- src/main/java/com/example/qpc/controller/CategoryController.java
- src/main/java/com/example/qpc/controller/ProductController.java
- src/main/java/com/example/qpc/dto/ProductDTO.java
- src/main/java/com/example/qpc/entity/CategoryEntity.java
- src/main/java/com/example/qpc/entity/ProductEntity.java
- src/main/java/com/example/qpc/repository/CategoryRepository.java
- src/main/java/com/example/qpc/service/CategoryService.java
- src/main/java/com/example/qpc/service/ProductService.java
> product 카테고리 추가 후 등록

- src/main/java/com/example/qpc/controller/ProductController.java
- src/main/java/com/example/qpc/service/ProductService.java
상품 저장 후 리스트 출력 및 상세 조회 
( 현 상태 리스트와 상세 조회 시 이미지 깨짐 추후 수정해야 함)
> 상품 저장 후 리스트 출력 및 상세 조회

- src/main/resources/templates/index.html
> 필요없는 코드 삭제 CSRF

- src/main/java/com/example/qpc/controller/ProductController.java
- src/main/java/com/example/qpc/entity/ProductEntity.java
- src/main/java/com/example/qpc/service/ProductService.java
(삭제는 가능하지만 수정은 카테고리 추가해서 수정해야함)
> 1차 수정 및 삭제

- src/main/resources/templates/component/adminNav.html
> adminNav_모달창정리_이미지틀추가

- src/main/java/com/example/qpc/controller/GameController.java
- src/main/java/com/example/qpc/dto/GameDTO.java
- src/main/java/com/example/qpc/entity/GameEntity.java
- src/main/java/com/example/qpc/entity/GameFileEntity.java
- src/main/java/com/example/qpc/repository/GameCategoryRepository.java
- src/main/java/com/example/qpc/repository/GameFileRepository.java
- src/main/java/com/example/qpc/repository/GameRepository.java
- src/main/java/com/example/qpc/service/GameCategoryService.java
- src/main/java/com/example/qpc/service/GameService.java
게임 카테고리 추가 후 저장
추후 수정 필요 할 수도..?
> 게임 카테고리 수정 및

- src/main/java/com/example/qpc/controller/GameController.java
- src/main/java/com/example/qpc/service/GameService.java
리스트에서 이미지 누르면 해당 게임 홈페이지로 이동 가능 
하지만 이미지 깨짐 추후 수정 필요
> 리스트 이동 및 삭제 가능

- src/main/resources/templates/component/adminNav.html
> adminNav빨간줄 수정

- src/main/java/com/example/qpc/config/WebConfig.java
- src/main/java/com/example/qpc/dto/ProductDTO.java
- src/main/java/com/example/qpc/entity/ProductEntity.java
- src/main/java/com/example/qpc/service/ProductService.java
> 이미지 띄워서 상품 리스트, 상세조회하기

- src/main/java/com/example/qpc/controller/AdminController.java
> 블랙 풀기,블랙수정 메서드 넣음

- src/main/resources/templates/index.html
> 회원가입할때 이메일인증해야 가입할 수 있도록 수정

- src/main/java/com/example/qpc/controller/ProductController.java
- src/main/java/com/example/qpc/entity/ProductEntity.java
- src/main/java/com/example/qpc/entity/ProductFileEntity.java
- src/main/java/com/example/qpc/service/ProductService.java
> 데이터베이스에 상품 이름이 null이 되는 오류 수정

- src/main/java/com/example/qpc/controller/GameController.java
- src/main/java/com/example/qpc/dto/GameCategoryDTO.java
- src/main/java/com/example/qpc/dto/GameDTO.java
- src/main/java/com/example/qpc/entity/GameCategoryEntity.java
- src/main/java/com/example/qpc/entity/GameEntity.java
- src/main/java/com/example/qpc/service/GameService.java
게임 등록 후 목록을 나타낼 때 이미지가 깨져서 나타나는 오류 수정
> 게임 등록 후 목록을 나타낼 때 이미지가 깨져서 나타나는 오류 수정

- src/main/java/com/example/qpc/controller/CategoryController.java
> 상품카테고리 주소 수정

- src/main/java/com/example/qpc/config/SecurityConfig.java
- src/main/java/com/example/qpc/controller/MemberController.java
- src/main/resources/application.yml
- src/main/resources/templates/index.html
메인 인덱스 수정
1. 아이디 찾기 기능 -> O
2. 비밀번호 찾기 기능 -> X
3. 아이디/비밀번호 모달창 X버튼 활성화 -> X
> Sw main index update

- src/main/resources/templates/index.html
index_modal-close 전체적용
index_로고svg효과
> Html0723_1

- src/main/java/com/example/qpc/controller/PaymentController.java
- src/main/java/com/example/qpc/dto/MemberDTO.java
- src/main/java/com/example/qpc/service/MemberService.java
카카오페이 결제 후 total,over 시간 누적합 수정
> 카카오페이 결제 후 total,over 시간 누적합 수정

- src/main/java/com/example/qpc/controller/AdminController.java
- src/main/resources/templates/component/adminNav.html
- src/main/resources/templates/index.html
> Sw admin update

- src/main/resources/templates/component/adminNav.html
> 게임등록 쪽 밑 마진과 버튼 부트스트랩 적용

- src/main/java/com/example/qpc/controller/MemberController.java
- src/main/resources/templates/component/sidebar.html
- src/main/resources/templates/memberPages/memberFood.html
- src/main/resources/templates/memberPages/memberMyPage.html
회원 메인 화면에서 내정보> 패스워드 입력 후 수정 삭제 모달창 띄우기
> 회원 메인 화면에서 내정보> 패스워드 입력 후 수정 삭제 모달창 띄우기

- src/main/resources/templates/index.html
> 카카오페이 요금충전 버튼 css수정

- src/main/java/com/example/qpc/controller/PaymentController.java
- src/main/resources/templates/component/sidebar.html
회원가입을 새로하고 카카오페이 요금충전을 한 후 로그인을 하면 403에러가 났는데 카카오페이를 한 후 세션을 비웠더니 해결됌
> 회원가입 카카오페이 요금충전 로그인 이상한거 수정

- src/main/java/com/example/qpc/controller/MemberController.java
- src/main/resources/templates/component/sidebar.html
- src/main/resources/templates/index.html
- src/main/resources/templates/memberPages/memberMain.html
> Sw member food
